2020-02-06 00:49:46,230 (189834/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-06 00:49:46,393 (189834/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 566, in connect\n    raise e\n  File "/usr/lib/python3.8/site-packages/pgcli/main.py", line 553, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 215, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.8/site-packages/pgcli/pgexecute.py", line 255, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
